### PR TITLE
Encryption setting

### PR DESCRIPTION
**Pull request by ymarcon**
Hi,

In order to offer some flexibility with the encryption, this PR suggests using an app setting for making available a crypto object. This object will be used to `encrypt` the secret before storage and `decrypt` it before validation. 

As an example, see this crypto setting:
https://github.com/obiba/amber/blob/main/src/crypto.js

### CODE REVIEW

**Comment by OnnoGabriel** [comment]
Hi @ymarcon, thank you very much! Such contributions are highly welcomed :-)

Just one question for clarification: You get  the crypto methods from the Feathers app configuration with `options.cryptoSetting` as the config key:  `const crypto = context.app.get(options.cryptoSetting)`. Is there a reason for this "detour" or could the  crypto methods  also be defined directly in the package options (without using the app config)?

**Comment by ymarcon** [comment]
I must admit it is a bit clumsy... I just wanted to reuse the encryption code I had in the app. The other option is of course to implement the mechanism internally, requiring several options: secret key, iv and algo name. I can amend this PR as you prefer.

**Comment by OnnoGabriel** [comment]
I get it now :-) How about this: The crypto methods are directly taken from the hook options: `const crypto = options.cryptoSetting;`. And the users can define any methods in the hook options. In your case, you could still use your methods from the app configuration by invoking the `totp2fa` hook like: 
```
totp2fa({
    cryptoSetting: context.app.get('key_to_crypto_config'),
    ...more settings...
})
```

This would be more flexible. Users do not have to use the app configuration, but they still can.

If you agree, you may update your PR. Or I could do it, too. I would also like to add some more docs about it and some tests.

**Comment by ymarcon** [comment]
Good idea, let's get the app out of this module. I'll amend the PR.

**Comment by ymarcon** [comment]
Now the option is called `cryptoUtil` and it is an object described by the interface `CryptoUtil`. Much cleaner! I let you complement this with docs and tests.

**Pull request merged**
